-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.Agenda_constraint exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| unique or primary key constraints on table "Agenda"

  - Agenda\_pkey - unique or primary key constraint

-}
type Agenda_constraint
    = Agenda_pkey


list : List Agenda_constraint
list =
    [ Agenda_pkey ]


decoder : Decoder Agenda_constraint
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "Agenda_pkey" ->
                        Decode.succeed Agenda_pkey

                    _ ->
                        Decode.fail ("Invalid Agenda_constraint type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : Agenda_constraint -> String
toString enum =
    case enum of
        Agenda_pkey ->
            "Agenda_pkey"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Agenda_constraint
fromString enumString =
    case enumString of
        "Agenda_pkey" ->
            Just Agenda_pkey

        _ ->
            Nothing
