-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (..)


type Agenda
    = Agenda


type Agenda_mutation_response
    = Agenda_mutation_response


type Consultation
    = Consultation


type Consultation_mutation_response
    = Consultation_mutation_response


type Patient
    = Patient


type Patient_Profession
    = Patient_Profession


type Patient_Profession_mutation_response
    = Patient_Profession_mutation_response


type Patient_mutation_response
    = Patient_mutation_response


type Profession
    = Profession


type Profession_mutation_response
    = Profession_mutation_response
