-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Consultation exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| An object relationship
-}
agenda : SelectionSet decodesTo Api.Object.Agenda -> SelectionSet decodesTo Api.Object.Consultation
agenda object_ =
    Object.selectionForCompositeField "Agenda" [] object_ identity


{-| An object relationship
-}
patient : SelectionSet decodesTo Api.Object.Patient -> SelectionSet decodesTo Api.Object.Consultation
patient object_ =
    Object.selectionForCompositeField "Patient" [] object_ identity


id_agenda : SelectionSet Int Api.Object.Consultation
id_agenda =
    Object.selectionForField "Int" "id_agenda" [] Decode.int


id_patient : SelectionSet Int Api.Object.Consultation
id_patient =
    Object.selectionForField "Int" "id_patient" [] Decode.int


indice_anxiete : SelectionSet Api.ScalarCodecs.Smallint Api.Object.Consultation
indice_anxiete =
    Object.selectionForField "ScalarCodecs.Smallint" "indice_anxiete" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecSmallint |> .decoder)


mode_de_reglement : SelectionSet String Api.Object.Consultation
mode_de_reglement =
    Object.selectionForField "String" "mode_de_reglement" [] Decode.string


mots_cles : SelectionSet String Api.Object.Consultation
mots_cles =
    Object.selectionForField "String" "mots_cles" [] Decode.string


prix : SelectionSet Api.ScalarCodecs.Money Api.Object.Consultation
prix =
    Object.selectionForField "ScalarCodecs.Money" "prix" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecMoney |> .decoder)
