-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Patient_Profession exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| An object relationship
-}
patient : SelectionSet decodesTo Api.Object.Patient -> SelectionSet decodesTo Api.Object.Patient_Profession
patient object_ =
    Object.selectionForCompositeField "Patient" [] object_ identity


{-| An object relationship
-}
profession : SelectionSet decodesTo Api.Object.Profession -> SelectionSet decodesTo Api.Object.Patient_Profession
profession object_ =
    Object.selectionForCompositeField "Profession" [] object_ identity


date_de_debut : SelectionSet Api.ScalarCodecs.Date Api.Object.Patient_Profession
date_de_debut =
    Object.selectionForField "ScalarCodecs.Date" "date_de_debut" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDate |> .decoder)


date_de_fin : SelectionSet (Maybe Api.ScalarCodecs.Date) Api.Object.Patient_Profession
date_de_fin =
    Object.selectionForField "(Maybe ScalarCodecs.Date)" "date_de_fin" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDate |> .decoder |> Decode.nullable)


id_patient : SelectionSet Int Api.Object.Patient_Profession
id_patient =
    Object.selectionForField "Int" "id_patient" [] Decode.int


id_profession : SelectionSet Int Api.Object.Patient_Profession
id_profession =
    Object.selectionForField "Int" "id_profession" [] Decode.int
