-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Profession exposing (..)

import Api.Enum.Patient_Profession_select_column
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


type alias PatientProfessionsOptionalArguments =
    { distinct_on : OptionalArgument (List Api.Enum.Patient_Profession_select_column.Patient_Profession_select_column)
    , limit : OptionalArgument Int
    , offset : OptionalArgument Int
    , order_by : OptionalArgument (List Api.InputObject.Patient_Profession_order_by)
    , where_ : OptionalArgument Api.InputObject.Patient_Profession_bool_exp
    }


{-| An array relationship

  - distinct\_on - distinct select on columns
  - limit - limit the number of rows returned
  - offset - skip the first n rows. Use only with order\_by
  - order\_by - sort the rows by one or more columns
  - where\_ - filter the rows returned

-}
patient_Professions : (PatientProfessionsOptionalArguments -> PatientProfessionsOptionalArguments) -> SelectionSet decodesTo Api.Object.Patient_Profession -> SelectionSet (List decodesTo) Api.Object.Profession
patient_Professions fillInOptionals object_ =
    let
        filledInOptionals =
            fillInOptionals { distinct_on = Absent, limit = Absent, offset = Absent, order_by = Absent, where_ = Absent }

        optionalArgs =
            [ Argument.optional "distinct_on" filledInOptionals.distinct_on (Encode.enum Api.Enum.Patient_Profession_select_column.toString |> Encode.list), Argument.optional "limit" filledInOptionals.limit Encode.int, Argument.optional "offset" filledInOptionals.offset Encode.int, Argument.optional "order_by" filledInOptionals.order_by (Api.InputObject.encodePatient_Profession_order_by |> Encode.list), Argument.optional "where" filledInOptionals.where_ Api.InputObject.encodePatient_Profession_bool_exp ]
                |> List.filterMap identity
    in
    Object.selectionForCompositeField "Patient_Professions" optionalArgs object_ (identity >> Decode.list)


id_profession : SelectionSet Int Api.Object.Profession
id_profession =
    Object.selectionForField "Int" "id_profession" [] Decode.int


profession : SelectionSet String Api.Object.Profession
profession =
    Object.selectionForField "String" "profession" [] Decode.string
