-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.Patient_Profession_constraint exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| unique or primary key constraints on table "Patient\_Profession"

  - Patient\_Profession\_pkey - unique or primary key constraint

-}
type Patient_Profession_constraint
    = Patient_Profession_pkey


list : List Patient_Profession_constraint
list =
    [ Patient_Profession_pkey ]


decoder : Decoder Patient_Profession_constraint
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "Patient_Profession_pkey" ->
                        Decode.succeed Patient_Profession_pkey

                    _ ->
                        Decode.fail ("Invalid Patient_Profession_constraint type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : Patient_Profession_constraint -> String
toString enum =
    case enum of
        Patient_Profession_pkey ->
            "Patient_Profession_pkey"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Patient_Profession_constraint
fromString enumString =
    case enumString of
        "Patient_Profession_pkey" ->
            Just Patient_Profession_pkey

        _ ->
            Nothing
